{-|-}
module Graphics.UI.GLCV.Key where

-- | Possible keys/buttons.
data Key = KNone
         | MouseWheelUp
         | MouseWheelDown
         | MouseLeft
         | MouseRight
         | MouseMiddle
         | A
         | B
         | C
         | D
         | E
         | F
         | G
         | H
         | I
         | J
         | K
         | L
         | M
         | N
         | O
         | P
         | Q
         | R
         | S
         | T
         | U
         | V
         | W
         | X
         | Y
         | Z
         | N0
         | N1
         | N2
         | N3
         | N4
         | N5
         | N6
         | N7
         | N8
         | N9
         | Equal
         | Minus
         | RightBracket
         | LeftBracket
         | Quote
         | Semicolon
         | Backslash
         | Comma
         | Slash
         | Period
         | Grave
         | KeypadDecimal
         | KeypadMultiply
         | KeypadPlus
         | KeypadClear
         | KeypadDivide
         | KeypadEnter
         | KeypadMinus
         | KeypadEquals
         | Keypad0
         | Keypad1
         | Keypad2
         | Keypad3
         | Keypad4
         | Keypad5
         | Keypad6
         | Keypad7
         | Keypad8
         | Keypad9
         | Return
         | Tab
         | Space
         | Delete
         | Escape
         | Command
         | Shift
         | CapsLock
         | Option
         | Control
         | RightShift
         | RightOption
         | RightControl
         | Function
         | VolumeUp
         | VolumeDown
         | Mute
         | F1
         | F2
         | F3
         | F4
         | F5
         | F6
         | F7
         | F8
         | F9
         | F10
         | F11
         | F12
         | F13
         | F14
         | F15
         | F16
         | F17
         | F18
         | F19
         | F20
         | Help
         | Home
         | Pageup
         | ForwardDelete
         | End
         | PageDown
         | LeftArrow
         | RightArrow
         | DownArrow
         | UpArrow
         | Scroll
         | NumLock
         | Clear
         | SysReq
         | Pause
         | Camera
         | Center
         | At
         | Sym
         deriving (Show, Enum)
